### ISSUE TITLE
webhooks on unbanned console errors do not appear 

### ISSUE THREAD

**Issue by adit4rt** [PmzHeroV69/BansWebhook#16]
Webhooks for Unbanned do not appear, console error when unbanning.

`10:24:01] [Craft Scheduler Thread - 102 - AdvancedBan/INFO]: Peko was successfully unbanned!
[10:24:01] [Server thread/ERROR]: Could not pass event RevokePunishmentEvent to BansWebhook v2.2
java.lang.NullPointerException: Cannot invoke "club.minnced.discord.webhook.WebhookClient.send(club.minnced.discord.webhook.send.WebhookEmbed, club.minnced.discord.webhook.send.WebhookEmbed[])" because "client" is null
	at ir.pmzhero.banswebhook.common.webhook.WebhookManager.sendWebhook(WebhookManager.java:36) ~[BansWebhook-2.2.jar:?]
	at ir.pmzhero.banswebhook.common.webhook.WebhookManager.sendPunishmentWebhook(WebhookManager.java:143) ~[BansWebhook-2.2.jar:?]
	at ir.pmzhero.banswebhook.common.advancedban.AdvancedBanEventHandler.handle(AdvancedBanEventHandler.java:34) ~[BansWebhook-2.2.jar:?]
	at ir.pmzhero.banswebhook.spigot.listener.AdvancedBanPunishmentListener.onRevokePunishment(AdvancedBanPunishmentListener.java:23) ~[BansWebhook-2.2.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor436.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-169]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-169]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-169]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at me.leoko.advancedban.bukkit.BukkitMethods.lambda$callRevokePunishmentEvent$8(BukkitMethods.java:375) ~[AdvancedBan-Bundle-2.3.0-RELEASE.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-169]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.1.jar:git-Paper-169]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1479) ~[paper-1.20.1.jar:git-Paper-169]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.1.jar:git-Paper-169]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1393) ~[paper-1.20.1.jar:git-Paper-169]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1170) ~[paper-1.20.1.jar:git-Paper-169]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-169]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
`

I'm using the latest version BansWebHook-2.2.jar

**Comment by PmzHeroV69** [comment]
Hello
If you have updated the plugin, you should regenerate the config to configure the unban webhooks

If you have this issue with other punishments too, you have configured your webhooks incorrectly

If you still have the issue after doing the steps i mentioned, please let me know. Thanks 😊
