### ISSUE TITLE
Error after updating LiteBans messages

### ISSUE THREAD

**Issue by Yoloman0013** [PmzHeroV69/BansWebhook#5]
- [Tue 18:48:53 ERROR club.minnced.discord.webhook.WebhookClient] Sending a webhook message failed with non-OK http response
club.minnced.discord.webhook.exception.HttpException: Request returned failure 400: {"code": 50035, "errors": {"embeds": {"0": {"thumbnail": {"url": {"_errors": [{"code": "URL_TYPE_INVALID_SCHEME", "message": "Scheme \"\" is not supported. Scheme must be one of ('http', 'https')."}]}}, "url": {"_errors": [{"code": "URL_TYPE_INVALID_SCHEME", "message": "Scheme \"\" is not supported. Scheme must be one of ('http', 'https')."}]}}}}, "message": "Invalid Form Body"}
    at BansWebhook-2.1.1.jar//club.minnced.discord.webhook.WebhookClient.failure(WebhookClient.java:757)
    at BansWebhook-2.1.1.jar//club.minnced.discord.webhook.WebhookClient.executePair(WebhookClient.java:832)
    at BansWebhook-2.1.1.jar//club.minnced.discord.webhook.WebhookClient.drainQueue(WebhookClient.java:801)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.lang.Thread.run(Thread.java:833)
  [Tue 18:48:57 INFO  Server/LoginListener] UUID of player Ghostx0013 is 9bb4fb5b-f1cf-3ac2-9f82-469f8a901f8f
  [Tue 18:48:57 INFO ] [SaberFactions] Ghostx0013 set autoLeave to false
  [Tue 18:48:57 INFO  Server/PlayerList] Ghostx0013[/90.139.182.158:49742] logged in with entity id 183717 at ([world]-46.550732799348125, 75.0, -217.73131104952319)

**Comment by PmzHeroV69** [comment]
Hello, is the issue still present in the new version?
