### ISSUE TITLE
Error with Webhooks not sending

### ISSUE THREAD

**Issue by Tejay17** [PmzHeroV69/BansWebhook#6]
> 2023-01-10 12:23:46,339 Webhook-RateLimit Thread WebhookID: 8748372434 ERROR Recursive call to appender Async
[12:23:46 ERROR]: [club.minnced.discord.webhook.WebhookClient] Sending a webhook message failed with non-OK http response
club.minnced.discord.webhook.exception.HttpException: Request returned failure 400: {"code": 50035, "errors": {"embeds": {"0": {"thumbnail": {"url": {"_errors": [{"code": "URL_TYPE_INVALID_SCHEME", "message": "Scheme \"\" is not supported. Scheme must be one of ('http', 'https')."}]}}, "url": {"_errors": [{"code": "URL_TYPE_INVALID_SCHEME", "message": "Scheme \"\" is not supported. Scheme must be one of ('http', 'https')."}]}}}}, "message": "Invalid Form Body"}
        at club.minnced.discord.webhook.WebhookClient.failure(WebhookClient.java:757) ~[BansWebhook-2.1.1.jar:?]
        at club.minnced.discord.webhook.WebhookClient.executePair(WebhookClient.java:832) ~[BansWebhook-2.1.1.jar:?]
        at club.minnced.discord.webhook.WebhookClient.drainQueue(WebhookClient.java:801) ~[BansWebhook-2.1.1.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]

**Comment by PmzHeroV69** [comment]
Hello, is this issue still present in the new version?
